Pronia/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }

    }
}

Pronia/Models/Color.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Pronia/Models/Plant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Plant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Column(TypeName = "decimal(6,2)")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string SKUCode { get; set; }
        public string Shipping { get; set; }
        public string Request { get; set; }
        public string Guarantee { get; set; }
        public int? ColorId { get; set; }
        public Color Color { get; set; }
        public int? SizeId { get; set; }
        public Size Size { get; set; }
        public List<PlantImage> PlantImages { get; set; }

    }
}

Pronia/Models/PlantImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class PlantImage
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public bool? IsMain { get; set; }
        public int PlantId { get; set; }
        public Plant Plant { get; set; }
    }
}

Pronia/Models/Size.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Size
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Pronia/Models/Slider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public byte Discount { get; set; }
        public string DiscoverUrl { get; set; }
    }
}

Pronia/ViewModels/HomeVM.cs
using Pronia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.ViewModels
{
    public class HomeVM
    {
        public List<Slider> Sliders { get; set; }
        public List<Client> Clients { get; set; }
        public List<Plant> Plants { get; set; }
       
    }
}

Pronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class ColorController : Controller
    {
        private readonly AppDbContext _context;

        public ColorController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Color> colors = await _context.Colors.ToListAsync();
            return View(colors);
        }
        public IActionResult Create()
        {
            return Json("Create");
        }
        public IActionResult Detail(int id)
        {
            return Json(id);
        }
        public IActionResult Edit(int id)
        {
            return Json(id);
        }
        public IActionResult Delete(int id)
        {
            return Json(id);
        }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class SizeController : Controller
    {
        private readonly AppDbContext _context;

        public SizeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Size> sizes = await _context.Sizes.ToListAsync();
            return View(sizes);
        }
        public IActionResult Create()
        {
            return Json("Create");
        }
        public IActionResult Detail(int id)
        {
            return Json(id);
        }
        public IActionResult Edit(int id)
        {
            return Json(id);
        }
        public IActionResult Delete(int id)
        {
            return Json(id);
        }
    }
}

Pronia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM model = new HomeVM
            {
                Sliders = await _context.Sliders.ToListAsync(),
                Clients = await _context.Clients.ToListAsync(),
                Plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync()
        };
            
            return View(model);
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create size</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Color color in Model)
            {
                <tr>
                    <td>
                        @color.Id
                    </td>
                    <td>
                        @color.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Size" asp-action="Detail" asp-route-id="@color.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="ms-2 edit">
                                <a class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                            </div>
                            <div class="ms-2 delete">
                                <a class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

Pronia/Areas/ProniaAdmin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Pronia/Areas/ProniaAdmin/Views/Size/Index.cshtml
@model List<Size>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create size</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Size size in Model)
            {
                <tr>
                    <td>
                        @size.Id
                    </td>
                    <td>
                        @size.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Size" asp-action="Detail" asp-route-id="@size.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="ms-2 edit">
                                <a class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                            </div>
                            <div class="ms-2 delete">
                                <a class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>